Fix potential ArgumentError in development
When operating in a development environment, changing
Griddler.configuration.processor_class can raise an

    ArgumentError: A copy of EmailProcessor has been removed from the module tree but is still active!

To prevent this, change our reference to the class to a string and
reload it when the class is reloaded (as it is in
Rails.env.development?) and constantize that string when needed.