Ensure the params[:recipient] can be split
We ran into an issue where we got a random failure on production of:

NoMethodError (undefined method `split' for nil:NilClass):
/var/www/apps/railsrumble/shared/bundle/ruby/2.0.0/bundler/gems/griddler-2f0f7b112d29/lib/griddler/adapters/mailgun_adapter.rb:28:in `recipients'

casting the param to_s will ensure even if it is nil split won't fail
with an error